

#(?????????????data-ids?group?data-id ?server-addr?namespace???????)#

## -----------------??????(?????????? log-enable: true)-------------- ##
nacos:
  config:
    bootstrap:
      log-enable: true # ??????????????????dubbo????????????
      enable: true # ????nacos.config.bootstrap.enable=true??????????

    max-retry: 10 # ??? ??????
    auto-refresh: false # ??? ???????? (false:???????,true:??????,???????????????autoRefreshed = true???????)
    config-retry-time: 3000 # ??? ????
    config-long-poll-timeout: 30000 # ??? ???????????
    enable-remote-sync-config: false # ??? ???????????????????????????????????
    #??nacos???????????; ??????nacos?????????????application.yml????????????nacos?????;????????
    remote-first: true

    # ??? data-ids  (??????,????????????? ?? ?????????)
    data-ids: order-service-dev
    group: DEFAULT_GROUP # ??? group-id
    type: yaml # ??? ??????
    server-addr: 81.70.33.19:8848
    #    namespace: # ????
    name: nacos
    password: nacos

    ext-config[0]:
      data-id: order-service-dev
      group: DEFAULT_GROUP
      namespace: 3f6704be-64d3-4856-95c5-9bf08982fd06      # ???? ??????? ???????  ???????????
      # ????????????    ???????? (false:???????,true:??????,???????????????autoRefreshed = true???????)
      auto-refresh: true
      type: yaml  # ?? {@link com.alibaba.nacos.api.config.ConfigType}
    ext-config[1]:
      data-id: binx-nacos
      group: DEFAULT_GROUP
      namespace: 3f6704be-64d3-4856-95c5-9bf08982fd06      # ???? ??????? ???????  ???????????
      # ????????????    ???????? (false:???????,true:??????,???????????????autoRefreshed = true???????)
      auto-refresh: true
      type: yaml  # ?? {@link com.alibaba.nacos.api.config.ConfigType}
  discovery:
    auto-register: true
    server-addr:  81.70.33.19:8848
    username: nacos
    password: nacos
    namespace: 3f6704be-64d3-4856-95c5-9bf08982fd06